Building DAG of jobs...
Job counts:
	count	jobs
	2	BAM_index
	1	all
	3

[Tue Nov 17 20:24:20 2020]
rule BAM_index:
    input: ../bam/20201117-293T-WGS_.DigenomeSeq_HEK4_Aligned_sortp.mapped_F1804_MAPQ20.bam
    output: ../bam/20201117-293T-WGS_.DigenomeSeq_HEK4_Aligned_sortp.mapped_F1804_MAPQ20_rmdup.bam, ../bam/20201117-293T-WGS_.DigenomeSeq_HEK4_Aligned_sortp.mapped_F1804_MAPQ20_rmdup.bam.bai
    jobid: 19
    reason: Missing output files: ../bam/20201117-293T-WGS_.DigenomeSeq_HEK4_Aligned_sortp.mapped_F1804_MAPQ20_rmdup.bam.bai, ../bam/20201117-293T-WGS_.DigenomeSeq_HEK4_Aligned_sortp.mapped_F1804_MAPQ20_rmdup.bam
    wildcards: date=20201117, cell=293T, seq=WGS, sample=DigenomeSeq_HEK4

RuleException in line 255 of /gpfs/user/zhaohuanan/3.project/22.2020-11_1112_JSK_DigenomeSeq_WGS/snakepipes_WGS-BWAmapping/Snakefile.py:
NameError: The name 'THREATS' is unknown in this context. Please make sure that you defined that variable. Also note that braces not used for variable access have to be escaped by repeating them, i.e. {{print $1}}
  File "/home/zhaohuanan/zhaohn_HD/miniconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 131, in run_jobs
  File "/home/zhaohuanan/zhaohn_HD/miniconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 140, in run
  File "/home/zhaohuanan/zhaohn_HD/miniconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 151, in _run
  File "/home/zhaohuanan/zhaohn_HD/miniconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 171, in printjob
  File "/home/zhaohuanan/zhaohn_HD/miniconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 157, in printjob
